import type { Product } from "@/lib/types";

export const seedProducts: Omit<Product, "id">[] = [
  {
    slug: "polo-technique-homme-noir",
    name: "Polo Technique Ghjucà",
    category: "Homme",
    price: 69,
    description:
      "Polo de padel en tissu technique respirant, coupe ajustée pour une liberté de mouvement totale sur le court.",
    details: [
      "Tissu technique 4-way stretch anti-transpiration",
      "Traitement anti-odeur",
      "Coupe ajustée athlétique",
      "Broderie Ghjucà et liseré or sur la poitrine",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Noir / Or",
    base: "black",
    accent: "gold",
  },
  {
    slug: "short-performance-homme-noir",
    name: "Short Performance",
    category: "Homme",
    price: 59,
    description:
      "Short léger et résistant pensé pour les déplacements rapides, avec poche zippée pour balle de padel.",
    details: [
      "Tissu stretch ultra-léger",
      "Poche zippée sécurisée",
      "Ceinture élastique ajustable",
      "Découpe articulée pour la mobilité",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Noir / Or",
    base: "black",
    accent: "gold",
  },
  {
    slug: "debardeur-technique-femme-blanc",
    name: "Débardeur Technique",
    category: "Femme",
    price: 49,
    description:
      "Débardeur technique à séchage rapide, coupe féminine ajustée pour un confort optimal en jeu.",
    details: [
      "Séchage rapide",
      "Coupe ajustée féminine",
      "Empiècements respirants dans le dos",
      "Signature Ghjucà rose sur la poitrine",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    color: "Blanc / Rose",
    base: "white",
    accent: "pink",
  },
  {
    slug: "jupe-short-femme-blanc",
    name: "Jupe-Short Performance",
    category: "Femme",
    price: 65,
    description:
      "Jupe-short technique avec short intégré, pensée pour combiner style et performance sur le court.",
    details: [
      "Short intégré pour une liberté totale",
      "Tissu 4-way stretch",
      "Poche balle de padel intégrée",
      "Taille haute confortable",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    color: "Blanc / Rose",
    base: "white",
    accent: "pink",
  },
  {
    slug: "veste-coupe-vent-unisexe-noir",
    name: "Veste Coupe-Vent",
    category: "Accessoires",
    price: 89,
    description:
      "Veste coupe-vent légère et compressible, indispensable pour l'échauffement et les jours de vent.",
    details: [
      "Déperlant et coupe-vent",
      "Compressible dans sa poche dédiée",
      "Coupe unisexe",
      "Fermeture éclair YKK",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "Noir / Or",
    base: "black",
    accent: "gold",
  },
  {
    slug: "polo-technique-femme-blanc",
    name: "Polo Technique Ghjucà",
    category: "Femme",
    price: 69,
    description:
      "Polo de padel technique en coupe féminine, respirant et extensible pour un confort maximal.",
    details: [
      "Tissu technique 4-way stretch",
      "Traitement anti-odeur",
      "Coupe ajustée féminine",
      "Broderie Ghjucà et liseré rose sur la poitrine",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    color: "Blanc / Rose",
    base: "white",
    accent: "pink",
  },
  {
    slug: "casquette-ghjuca-noir",
    name: "Casquette Ghjucà",
    category: "Accessoires",
    price: 29,
    description: "Casquette technique légère avec bandeau anti-transpiration et logo brodé.",
    details: [
      "Tissu léger et respirant",
      "Bandeau anti-transpiration",
      "Taille ajustable",
      "Logo Ghjucà brodé or",
    ],
    sizes: ["Taille unique"],
    color: "Noir / Or",
    base: "black",
    accent: "gold",
  },
  {
    slug: "sac-padel-ghjuca-noir",
    name: "Sac de Padel Ghjucà",
    category: "Accessoires",
    price: 119,
    description:
      "Sac de padel spacieux avec compartiment ventilé pour les raquettes et poche chaussures dédiée.",
    details: [
      "Compartiment raquettes rembourré",
      "Poche chaussures ventilée",
      "Bandoulière réglable",
      "Tissu déperlant résistant",
    ],
    sizes: ["Taille unique"],
    color: "Noir / Or",
    base: "black",
    accent: "gold",
  },
];
